### ISSUE TITLE
Extract linting to separate project

### ISSUE THREAD

**Issue by sdepold** [oxala/marko-tester#12]
In case I want to use the eslint settings from marko-tester in a project that doesn't use marko at all, then it seems a bit odd to install a marko-tester. Would it make sense to extract the linting part to a separate project and to use that in marko-tester?

**Comment by darkwebdev** [comment]
What about using separate package with ebay config, so that any project can just use eslint with it?

**Comment by oxala** [comment]
`ebay-config` is that a real thing?

sdepold, interesting suggestion. I guess it depends on a use-case. We can talk more.

**Comment by darkwebdev** [comment]
please check #13

**Comment by oxala** [comment]
Done some time ago. https://www.npmjs.com/package/eslint-config-marko-tester
