### ISSUE TITLE
Coverage report fails if module contains '$' string

### ISSUE THREAD

**Issue by abiyasa** [oxala/marko-tester#17]
I found very strange bug when you run marko-tester for coverage report.

I made a branch containing 1 sample component as part of the integration test: https://github.com/abiyasa/marko-tester/tree/bug/require-with-dollar

If you run `npm run integration-test`, everything's fine. 
However, when you run coverage test `node ./source/markotester test --no-lint`, it fails with message:

> Error: Cannot find module "/marko-tester$6.16.5/test/component-with-require-dollar/generateLabel" from "/marko-tester$6.16.5/test/component-with-require-dollar"

This is because we have '$' inside function generateLabel. 

```
module.exports = function (label) {
  return '$' + label + '$';
};
```

The funny thing is, if you replace '$' with '#', then everything is ok.

**Comment by abiyasa** [comment]
I peek into folder `/static/source/marko-tester$6.16.5/test/component-with-require-dollar/generateLabel.js`, it seems that marko-tester (or maybe lasso) replaced `'$'` with `'});` which causing require to fail.

when using '$':

```
module.exports = function (label) {
    __cov_UCovfpKEOyIuAVBV8iqlQw.f['1']++;
    __cov_UCovfpKEOyIuAVBV8iqlQw.s['2']++;
    return '}); + label + '});;
};
```

Replacing '$' with '#':

```
module.exports = function (label) {
    __cov_UCovfpKEOyIuAVBV8iqlQw.f['1']++;
    __cov_UCovfpKEOyIuAVBV8iqlQw.s['2']++;
    return '#' + label + '#';
};
```

Funny thing that this only happens when you do coverage test.

**Comment by oxala** [comment]
Interesting. Feels like istanbul might change the code. But i highly doubt that. Will take a look.

**Comment by oxala** [comment]
Interestingly enough. Function `.replace` was doing this. Fixed.
