### ISSUE TITLE
Support for eslint comment for embed configuration

### ISSUE THREAD

**Issue by abiyasa** [oxala/marko-tester#18]
It seems that marko-tester by default does not allow any inline config for eslint (https://github.com/oxala/marko-tester/blob/master/source/testers/lint.js#L36). This means that any eslint comment will not work (e.g `/* eslint no-plusplus: 0 */`).

It's true that you should not abuse eslint comment, but without this feature, linting becoming less flexible. If you want to ignore or set any rules to warning instead of error, you have to modify the eslint config. There are cases where you need to ignore some rules, e.g on fixture or test codes, or you just disagree with some coding style.

**Comment by oxala** [comment]
I don't really want to allow that. Because of people habits to suppress the error instead of fixing the cause. :(

**Comment by oxala** [comment]
No more eslint within this...
